package com.example.demo.model;

import lombok.*;
import javax.persistence.Entity;

@Entity
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@ToString
public class H2Entity extends BaseEntity {
    private String first;
    private String last;
    private String email;
    // constructors, getters and setters generated by lombok.
}
