package com.example.demo.model.user;

import lombok.*;
import org.springframework.data.mongodb.core.mapping.Document;

import javax.persistence.Entity;

@Entity
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@ToString
@Document(collection = "users")
public class AuthenticatedUser extends User {
    private String token;
    // constructors, getters and setters generated by lombok.
    public AuthenticatedUser(User usr){
        super(usr.getUserName(),usr.getPassword(),usr.getEmail());
        this.token=usr.getId();
    }
}
