package com.example.demo.model.user;

import com.example.demo.model.BaseEntity;
import lombok.*;
import org.springframework.data.mongodb.core.mapping.Document;

import javax.persistence.Entity;

@Entity
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@ToString
@Document(collection = "users")
public class User extends BaseEntity {
    private String userName;
    private String password;
    private String email;
    // constructors, getters and setters generated by lombok.
}
